version: "3"
services:
  server:
    image: gitea/gitea:1.20.0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - ./gitea_data:/data
    ports:
      - "3000:3000"
      - "10022:22"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ./gitea_postgres_data:/var/lib/postgresql/data

volumes:
  gitea_data:
  gitea_postgres_data: