version: "3"
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    networks:
      - gitea_net
    volumes:
      - ./gitea_data:/data
      - ./gitea_conf:/data/gitea/conf
    ports:
      - "3000:3000"
      - "10022:22"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea_net
    volumes:
      - ./gitea_postgres_data:/var/lib/postgresql/data

  act_runner:
    image: gitea/act_runner:latest
    container_name: act_runner
    restart: always
    depends_on:
      - gitea
    networks:
      - gitea_net
    environment:
      - CONFIG_FILE=/config.yaml
      - GITEA_INSTANCE_URL=http://gitea:3000/
      - GITEA_RUNNER_REGISTRATION_TOKEN=tOCwFvUOIFYzQCnc7MVt3z0OwEewLAhTUyZ4TUTv
      - GITEA_RUNNER_NAME=act_runner
      # runs-on 的标签实际上是下面这个，上面的只是名字
      # GITEA_RUNNER_LABELS: "ubuntu-latest"
    volumes:
      - ./act_runner_data/config.yaml:/config.yaml
      - ./act_runner_data/data:/data
      - ./act_runner_data/cache:/root/.cache
      - /var/run/docker.sock:/var/run/docker.sock

# volumes:
#   gitea_data:
#   gitea_postgres_data:

networks:
  gitea_net: